language: dart
sudo: required
dart:
  - stable
addons:
  postgresql: "9.6"
#addons:
#  postgresql: '12'
#  apt:
#    packages:
#      - postgresql-12
#      - postgresql-client-12
#  env:
#    - TOXENV=py38
#    - PGVER=12
#    - PSYCOPG3_IMPL=ctypes
#    - PGPORT=5434
services:
  - postgresql
before_script:
#set PGPASSWORD=s1sadm1n
#psql.exe -h 127.0.0.1 -U postgres -p 5434 -w -c "create database banco_teste;" on windows
#psql.exe -h 127.0.0.1 -U postgres -p 5434 -w -d banco_teste -c "CREATE TABLE public.pessoas ( id serial NOT NULL , nome varchar(255), telefone varchar(255) , cpf varchar(255) , CONSTRAINT pessoas_pkey PRIMARY KEY (id) );"
  - sudo cp ci/pg_hba.conf /etc/postgresql/9.6/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart  
  #- psql -c 'CREATE ROLE sisadmin LOGIN SUPERUSER PASSWORD 's1sadm1n';' -U postgres
  - psql -c 'create user sisadmin with SUPERUSER createdb;' -U postgres
  - psql -c "alter user sisadmin with password 's1sadm1n';" -U postgres
  - psql -c 'create database banco_teste;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE banco_teste TO sisadmin;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sisadmin;' -U postgres -d banco_teste
  - psql -c 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sisadmin;' -U postgres -d banco_teste
  - psql -c 'create user darttrust with createdb;' -U postgres
  - psql -c 'grant all on database banco_teste to darttrust;' -U postgres
  - export PGPASSWORD='s1sadm1n'
  - echo $PGPASSWORD
  - psql -c 'CREATE TABLE public.pessoas ( id serial NOT NULL , nome varchar(255), telefone varchar(255) , cep varchar(255) , CONSTRAINT pessoas_pkey PRIMARY KEY (id) );' -U sisadmin -d banco_teste
  - psql -c "INSERT INTO pessoas (nome,telefone,cep) VALUES ('Isaque', '99701-5305', '54654');" -U sisadmin -d banco_teste
  - psql -c "SELECT * FROM pessoas;" -U sisadmin -d banco_teste
  - psql -c "SHOW config_file" -U sisadmin -d banco_teste
  - psql -c "SELECT version();" -U sisadmin -d banco_teste
  #- sudo sed -i 's/^port.*/port = 5434/' /etc/postgresql/9.6/main/postgresql.conf 
  #- sudo sed -i 's/port = 5433/port = 5434/' /etc/postgresql/9.6/main/postgresql.conf
  #- sudo sed -i 's/port = 5432/port = 5434/' /etc/postgresql/9.6/main/postgresql.conf
  - cat /etc/postgresql/9.6/main/postgresql.conf
  - pub get
dart_task:
# - test: --run-skipped -r expanded -j 1
  - test: --concurrency 1  --chain-stack-traces
#  - dartfmt -w ./
#  - dartanalyzer: --fatal-infos --fatal-warnings .

#after_success: bash ci/after_script.sh
branches:
  only:
    - master
    

